app:
  image: 10.100.198.200:5000/calc-app
  volumes:
    - ./client/bower_components:/client/bower_components
    - ./client/node_modules:/client/node_modules
  ports:
    - 8080:8080

tests:
  image: 10.100.198.200:5000/calc-app-tests
  volumes:
    - ./target/scala-2.10:/source/target/scala-2.10
    - ./src:/source/src
    - ./client:/source/client
