FROM debian:jessie

ENV VERSION 1.0

RUN apt-get update

# CUrl
RUN apt-get -y install curl

# Dependencies
RUN curl -sL https://deb.nodesource.com/setup_0.12 | bash -
RUN echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN curl -sL https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo "deb http://packages.linuxmint.com debian import" >> /etc/apt/sources.list

# Mongo, NodeJS, Git, SBT, xvfb
RUN apt-get update && \
    apt-get -y --fix-missing install wget bzip2 make g++ && \
    apt-get -y --force-yes --fix-missing install --no-install-recommends mongodb nodejs git sbt xvfb && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Scala
RUN curl -O -q http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.deb && \
    dpkg -i scala-2.11.5.deb && \
    rm scala-2.11.5.deb

# bower
RUN npm install -g bower

# Dirs
RUN mkdir /source

ADD project /source/project
ADD build.sbt /source/build.sbt
ADD client/bower.json /source/client/bower.json
ADD client/package.json /source/client/package.json
ADD client/wct.conf.js /source/client/wct.conf.js
ADD run_tests.sh /source/run_tests.sh

RUN chmod +x /source/run_tests.sh

# Dependencies
RUN cd /source && sbt update

WORKDIR /source

CMD ["/source/run_tests.sh"]

EXPOSE 8080
